"use client";
import React, { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";

function Rv({ children, d = 0 }: { children: React.ReactNode; d?: number }) {
  return (
    <motion.div initial={{ opacity: 0, y: 35 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-50px" }} transition={{ delay: d, duration: 0.6, ease: [0.16, 1, 0.3, 1] }}>
      {children}
    </motion.div>
  );
}

/* ── Data ── */
const heroStats = [
  { val: "35%", label: "More Deals Closed" },
  { val: "50%", label: "Less Manual Work" },
  { val: "2.4x", label: "Faster Response Time" },
  { val: "24/7", label: "AI Availability" },
  { val: "98%", label: "Client Satisfaction" },
];

const painPoints = [
  "Leads go cold because follow-up takes too long — 78% of buyers choose the vendor that responds first.",
  "Sales reps spend up to 65% of their time on non-selling activities: data entry, scheduling, email drafting, and status updates.",
  "CRMs are full of incomplete data because manual input gets skipped under pressure.",
  "Phone calls go unanswered. Chat windows sit idle. Email sequences get abandoned after one or two touches.",
  "Marketing and sales operate in silos — leads generated by marketing campaigns disappear into a black hole.",
  "Enterprise teams have the budget to patch these problems with dozens of disconnected tools. SMBs often have nothing.",
  "AI is changing the competitive landscape — and companies not integrating AI into their sales process are already falling behind.",
];

const platformPillars = [
  { icon: "🤖", title: "AI Chatbots", desc: "Deploy intelligent, conversational chatbots across your website and digital touchpoints. Qualify leads, answer questions, schedule appointments, and route high-intent prospects — all without human intervention.", color: "#10B981" },
  { icon: "📧", title: "AI Email Bots & Automation", desc: "Intelligent email sequences that adapt in real time based on engagement. Our AI analyzes open rates, click behavior, and response patterns to personalize every message and optimize send timing.", color: "#3B82F6" },
  { icon: "📞", title: "AI Phone Bots & Voice", desc: "Outbound and inbound AI phone bots that sound natural, handle objections, qualify prospects, and transfer ready-to-buy leads directly to your sales team — live.", color: "#8B5CF6" },
  { icon: "📊", title: "Intelligent CRM", desc: "A CRM that auto-logs every interaction, scores leads based on real behavior, forecasts deal probability, and surfaces the actions most likely to move each deal forward.", color: "#F59E0B" },
  { icon: "🔗", title: "Aqurion Ecosystem", desc: "Connects natively with Aqurion Marketing, Aqurion Development, and Aqurion AI. Plus 250+ external integrations including HubSpot, Salesforce, Slack, and more.", color: "#06B6D4" },
  { icon: "📈", title: "Revenue Intelligence", desc: "Live dashboards showing pipeline health, rep performance, channel conversion rates, AI bot metrics, and revenue forecasts — all in one view.", color: "#EF4444" },
];

const chatbotCapabilities = [
  "Greet and qualify every visitor in real time — no lead falls through the cracks.",
  "Ask intelligent discovery questions tailored to your product, service, and industry.",
  "Answer detailed product and service questions using your knowledge base.",
  "Book meetings directly into your sales team's calendar.",
  "Route high-intent leads to a live rep instantly, with full conversation context.",
  "Handle objections using proven response frameworks customized to your sales process.",
  "Operate in multiple languages for international sales teams.",
];

const emailCapabilities = [
  "Launch personalized multi-touch sequences immediately when a lead is created.",
  "Adapt messaging based on open rates, link clicks, replies, and deal stage.",
  "A/B test subject lines, content, and CTAs continuously — optimizing automatically.",
  "Detect reply intent and route accordingly.",
  "Sync with CRM data to surface the right message for each segment.",
  "Auto-pause sequences when a lead replies or books a call.",
];

const phoneCapabilities = [
  "Answer every inbound call immediately — no hold times, no missed leads.",
  "Qualify callers with intelligent, conversational discovery questions.",
  "Transfer hot leads to a live rep with a warm handoff and full call summary.",
  "Execute high-volume outbound call campaigns with AI-driven personalization.",
  "Detect answering machines vs. live pickups and respond appropriately.",
  "Escalate interested prospects to a live rep mid-call when intent signals are detected.",
];

const crmFeatures = [
  { title: "Auto-Logging Across Every Channel", desc: "Every call, email, chat, SMS, and meeting is automatically captured with AI-generated summaries, sentiment scores, and action items." },
  { title: "AI Lead Scoring", desc: "Every lead receives a dynamic score based on engagement behavior, demographic fit, company size, deal stage activity, and predictive close probability." },
  { title: "Deal Health Monitoring", desc: "Aqurion's AI monitors every active deal for risk signals — stalled conversations, declining engagement, missed follow-ups — and alerts your team before a deal goes cold." },
  { title: "Intelligent Pipeline Forecasting", desc: "Real-time revenue forecasting built on actual deal behavior — not rep opinion. Aqurion analyzes historical close rates and engagement velocity." },
  { title: "Automated Task Management", desc: "The CRM generates and assigns tasks automatically based on deal events, time triggers, and AI recommendations. No follow-up gets forgotten." },
  { title: "360° Contact Intelligence", desc: "Every contact record is enriched with company data, social profiles, interaction history, engagement scores, and AI-generated talking points." },
];

const caseStudies = [
  {
    tag: "ENTERPRISE — FINANCIAL SERVICES", title: "How a National Insurance Group Cut Lead Response Time from 4 Hours to 4 Minutes",
    profile: "Multi-regional insurance brokerage with 280 sales representatives across 14 states, processing 6,000+ inbound leads per month.",
    results: ["Lead response time: 4.2 hours → under 4 minutes", "Contact rate increased by 61%", "Pipeline volume grew 44% in 90 days", "Manual data entry reduced by 58%", "First-year revenue recovery: $2.8M"],
    color: "#10B981",
  },
  {
    tag: "MID-MARKET — B2B SaaS", title: "AI-Powered Outbound Transformed a SaaS Company's Trial-to-Paid Conversion Rate",
    profile: "Series B SaaS company, 45 employees, 12,000 free trial users per month, 8 SDRs.",
    results: ["Trial-to-paid conversion: 6.2% → 14.8% in 60 days", "SDR capacity effectively tripled", "Time-to-close: 22 days → 13 days", "CAC decreased by 34%", "ARR grew 112% year-over-year"],
    color: "#3B82F6",
  },
  {
    tag: "SMB — PROFESSIONAL SERVICES", title: "A Three-Person Consulting Firm Stopped Losing Leads to Larger Competitors",
    profile: "Boutique HR consulting firm, 3 principals, 40-60 inbound inquiries per month.",
    results: ["Response time: 12-48 hours → under 2 minutes", "Inquiry-to-call booked: 31% → 68%", "Client acquisition increased 85%", "6 hours/week reclaimed per principal", "Two Fortune 500 contracts in 90 days"],
    color: "#8B5CF6",
  },
  {
    tag: "ENTERPRISE — RETAIL & E-COMMERCE", title: "Fortune 500 Retailer Deployed AI Sales Bots Across 2,400 Locations",
    profile: "National retail chain, 2,400 locations, 18,000 employees, $340M B2B wholesale division.",
    results: ["72% of routine inquiries handled by AI", "Proactive outreach capacity increased 3.1x", "Wholesale revenue grew 31% in year one", "New account acquisition increased 44%", "Account managers report feeling 'like actual salespeople again'"],
    color: "#F59E0B",
  },
  {
    tag: "STARTUP — REAL ESTATE TECHNOLOGY", title: "Pre-Revenue Startup Closed $1.2M ARR Using Aqurion Sales as Entire Sales Infrastructure",
    profile: "Pre-revenue PropTech startup, 7-person team, targeting commercial real estate brokerages.",
    results: ["First enterprise contract ($180K ARR) closed in 34 days", "$1.2M ARR in first 6 months", "Average sales cycle: 47 days (vs 90-day benchmark)", "100% pipeline managed without a sales hire", "Series A secured, citing Aqurion as key proof point"],
    color: "#06B6D4",
  },
];

const audiences = [
  {
    title: "Startups & Early-Stage", desc: "You don't have a 20-person sales team. Aqurion Sales gives you the infrastructure of a mature organization at a fraction of the cost.",
    bullets: ["Deploy AI chatbots before you have a sales team.", "Automate outbound outreach at scale.", "Track every interaction without manual data entry.", "Look and operate like a company 10x your size — from day one."],
    icon: "🚀",
  },
  {
    title: "Mid-Market ($10M–$500M)", desc: "Replace fragmented tools with a single, integrated platform that gives your team the intelligence to grow revenue without growing headcount.",
    bullets: ["Replace fragmented tools with a single platform.", "Automate the first 3–5 touches in every sequence.", "Real-time pipeline visibility you can act on.", "Align marketing and sales around shared data."],
    icon: "📊",
  },
  {
    title: "Enterprise ($500M+)", desc: "At enterprise scale, a 3% improvement in lead contact rate creates millions of dollars in revenue impact.",
    bullets: ["Deploy AI phone, email, and chat at thousands of touchpoints.", "Integrate with existing CRM and ERP infrastructure.", "Access Aqurion AI's advanced predictive intelligence.", "Dedicated implementation support and enterprise SLAs."],
    icon: "🏢",
  },
];

const testimonials = [
  { quote: "Aqurion Sales did something we'd been trying to do for three years: it actually aligned our marketing and sales operations. The AI phone bot alone has changed how we think about inbound capacity.", author: "VP of Sales", company: "National Financial Services Group", type: "Enterprise" },
  { quote: "Within 60 days, Aqurion had automated our entire outreach process, our trial conversion rate nearly doubled, and our SDRs were finally doing the job they were hired to do. It's the best decision we've made as a company.", author: "CEO", company: "Series B SaaS Company", type: "Mid-Market" },
  { quote: "The chatbot qualifies prospects, books calls, and sends follow-ups while I'm delivering work for existing clients. We landed two Fortune 500 clients in the first quarter after going live.", author: "Principal", company: "Boutique HR Consulting Firm", type: "SMB" },
  { quote: "We had a product and a market but no sales infrastructure. Aqurion Sales was our entire go-to-market engine from day one. We closed $1.2M in ARR in six months without a sales hire.", author: "Co-Founder", company: "PropTech Startup", type: "Startup" },
];

const integrations = {
  "CRM & Sales": ["HubSpot", "Salesforce", "Pipedrive", "Zoho CRM"],
  "Communication": ["Slack", "Microsoft Teams", "Google Workspace", "Zoom"],
  "Marketing": ["Mailchimp", "ActiveCampaign", "Marketo", "Google Ads"],
  "E-Commerce": ["Shopify", "WooCommerce", "BigCommerce"],
  "Automation": ["Zapier", "Make (Integromat)", "n8n"],
  "Support": ["Zendesk", "Intercom", "Freshdesk"],
  "Payments": ["Stripe", "Square", "Oracle Merchant Services"],
};

const trustSignals = [
  "No long-term contracts required to get started",
  "Implementation support included on all plans",
  "Enterprise custom deployments available",
  "SOC 2 compliant data infrastructure",
  "Native integration with Oracle Merchant Services",
  "Backed by the Aqurion Holdings ecosystem",
];

const aiSteps = [
  { num: "01", title: "Discovery", desc: "We map your current sales process, identify bottlenecks, and quantify the revenue impact of automation opportunities." },
  { num: "02", title: "Design", desc: "We build an AI automation architecture tailored to your product, market, buyer journey, and team structure." },
  { num: "03", title: "Deploy", desc: "We implement chatbots, email bots, phone bots, and CRM configuration — with full testing before going live." },
  { num: "04", title: "Optimize", desc: "We monitor performance, run continuous A/B testing, and refine AI behavior based on real conversion data." },
  { num: "05", title: "Evolve", desc: "As your business grows and AI capabilities advance, we scale and evolve your implementation to keep you ahead." },
];

/* ── Page ── */
export default function SalesPage() {
  const bp = process.env.NODE_ENV === "development" ? "/sales" : "";
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [activeTab, setActiveTab] = useState(0);
  const [expandedCase, setExpandedCase] = useState<number | null>(null);

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=Space+Grotesk:wght@400;500;600;700&display=swap');
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0;}
        html{scroll-behavior:smooth;}
        .sl{background:#FAFBFD;color:#0F172A;min-height:100vh;font-family:'Inter',sans-serif;overflow-x:hidden;}

        /* NAV */
        .sl-nav{position:fixed;top:0;left:0;right:0;z-index:100;display:flex;align-items:center;justify-content:space-between;padding:1rem 3rem;background:rgba(250,251,253,0.88);backdrop-filter:blur(24px);border-bottom:1px solid rgba(0,0,0,0.04);}
        .sl-nav-logo{display:flex;align-items:center;gap:0.6rem;font-size:1rem;font-weight:700;text-decoration:none;color:#0F172A;}
        .sl-nav-logo img{width:32px;height:32px;border-radius:10px;}
        .sl-nav-links{display:flex;align-items:center;gap:2rem;}
        .sl-nav-link{font-size:0.82rem;font-weight:500;color:rgba(15,23,42,0.45);text-decoration:none;transition:color 0.2s;}
        .sl-nav-link:hover{color:#0F172A;}
        .sl-cta{padding:0.55rem 1.5rem;border-radius:50px;background:#10B981;color:#fff;font-weight:700;font-size:0.82rem;border:none;cursor:pointer;text-decoration:none;transition:all 0.3s;display:inline-block;}
        .sl-cta:hover{transform:translateY(-2px);box-shadow:0 8px 30px rgba(16,185,129,0.25);}
        .sl-cta-outline{padding:0.55rem 1.5rem;border-radius:50px;background:transparent;color:#10B981;font-weight:700;font-size:0.82rem;border:2px solid #10B981;cursor:pointer;text-decoration:none;transition:all 0.3s;display:inline-block;}
        .sl-cta-outline:hover{background:#10B981;color:#fff;}

        /* HERO */
        .sl-hero{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:8rem 2rem 4rem;position:relative;overflow:hidden;}
        .sl-hero-bg{position:absolute;inset:0;background:linear-gradient(180deg,#ECFDF5 0%,#F0FDF4 40%,#FAFBFD 100%);}
        .sl-hero-orb1{position:absolute;top:10%;right:15%;width:400px;height:400px;border-radius:50%;background:rgba(16,185,129,0.06);filter:blur(80px);animation:slFloat 10s ease-in-out infinite;}
        .sl-hero-orb2{position:absolute;bottom:15%;left:10%;width:350px;height:350px;border-radius:50%;background:rgba(59,130,246,0.04);filter:blur(80px);animation:slFloat 12s ease-in-out infinite reverse;}
        @keyframes slFloat{0%,100%{transform:translate(0,0);}50%{transform:translate(25px,-25px);}}
        .sl-hero-content{position:relative;z-index:1;max-width:800px;}
        .sl-eyebrow{display:inline-flex;align-items:center;gap:0.5rem;padding:0.4rem 1.2rem;border-radius:50px;font-size:0.72rem;font-weight:600;background:rgba(16,185,129,0.08);color:#10B981;border:1px solid rgba(16,185,129,0.12);margin-bottom:2rem;letter-spacing:0.04em;}
        .sl-hero h1{font-family:'Space Grotesk',sans-serif;font-size:clamp(2.8rem,6vw,4.5rem);font-weight:700;line-height:1.08;letter-spacing:-0.04em;margin-bottom:1.5rem;}
        .sl-grad{background:linear-gradient(135deg,#10B981,#059669);-webkit-background-clip:text;-webkit-text-fill-color:transparent;}
        .sl-hero-sub{font-size:1.05rem;color:rgba(15,23,42,0.5);max-width:620px;line-height:1.8;margin:0 auto 1rem;}
        .sl-hero-body{font-size:0.88rem;color:rgba(15,23,42,0.35);max-width:600px;line-height:1.7;margin:0 auto 1.5rem;}
        .sl-hero-proof{font-size:0.75rem;color:rgba(15,23,42,0.3);margin-bottom:2.5rem;font-style:italic;}
        .sl-hero-btns{display:flex;gap:1rem;justify-content:center;flex-wrap:wrap;}

        /* STATS BAR */
        .sl-stats{display:grid;grid-template-columns:repeat(5,1fr);gap:1px;margin:0 3rem;border-radius:20px;overflow:hidden;background:rgba(0,0,0,0.04);position:relative;z-index:2;margin-top:-3rem;}
        .sl-stat{background:#fff;padding:2.5rem 1.5rem;text-align:center;}
        .sl-stat-val{font-family:'Space Grotesk',sans-serif;font-size:2rem;font-weight:700;color:#10B981;}
        .sl-stat-label{font-size:0.68rem;color:rgba(15,23,42,0.3);text-transform:uppercase;letter-spacing:0.12em;margin-top:0.25rem;}

        /* SECTIONS */
        .sl-section{padding:6rem 2rem;max-width:1100px;margin:0 auto;}
        .sl-section-wide{padding:6rem 2rem;max-width:1300px;margin:0 auto;}
        .sl-label{font-size:0.68rem;font-weight:700;text-transform:uppercase;letter-spacing:0.2em;color:#10B981;margin-bottom:0.75rem;}
        .sl-title{font-family:'Space Grotesk',sans-serif;font-size:clamp(2rem,4vw,2.8rem);font-weight:700;letter-spacing:-0.03em;margin-bottom:1rem;line-height:1.1;}
        .sl-subtitle{font-size:0.95rem;color:rgba(15,23,42,0.4);max-width:700px;line-height:1.8;margin-bottom:3rem;}

        /* PAIN POINTS */
        .sl-pain-grid{display:grid;gap:0.75rem;max-width:800px;}
        .sl-pain{display:flex;align-items:flex-start;gap:1rem;padding:1.25rem 1.5rem;border-radius:14px;background:#fff;border:1px solid rgba(0,0,0,0.04);transition:all 0.3s;}
        .sl-pain:hover{border-color:rgba(239,68,68,0.15);transform:translateX(4px);}
        .sl-pain-icon{width:28px;height:28px;border-radius:8px;background:rgba(239,68,68,0.06);display:flex;align-items:center;justify-content:center;font-size:0.85rem;flex-shrink:0;margin-top:2px;}
        .sl-pain-text{font-size:0.88rem;color:rgba(15,23,42,0.55);line-height:1.7;}

        /* PLATFORM PILLARS */
        .sl-pillars{display:grid;grid-template-columns:repeat(3,1fr);gap:1.25rem;}
        .sl-pillar{padding:2.5rem;border-radius:20px;background:#fff;border:1px solid rgba(0,0,0,0.04);transition:all 0.4s;position:relative;overflow:hidden;}
        .sl-pillar::before{content:'';position:absolute;bottom:0;left:0;right:0;height:3px;background:var(--accent);transform:scaleX(0);transition:transform 0.4s;transform-origin:left;}
        .sl-pillar:hover::before{transform:scaleX(1);}
        .sl-pillar:hover{transform:translateY(-6px);box-shadow:0 20px 50px rgba(0,0,0,0.06);}
        .sl-pillar-icon{font-size:1.5rem;margin-bottom:1.25rem;display:inline-flex;width:56px;height:56px;border-radius:16px;align-items:center;justify-content:center;background:rgba(16,185,129,0.06);}
        .sl-pillar-title{font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:1.05rem;margin-bottom:0.5rem;}
        .sl-pillar-desc{font-size:0.85rem;color:rgba(15,23,42,0.4);line-height:1.7;}

        /* TABS */
        .sl-tabs{display:flex;gap:0.5rem;margin-bottom:2.5rem;flex-wrap:wrap;}
        .sl-tab{padding:0.6rem 1.5rem;border-radius:50px;font-size:0.82rem;font-weight:600;border:1px solid rgba(0,0,0,0.06);background:#fff;color:rgba(15,23,42,0.45);cursor:pointer;transition:all 0.3s;}
        .sl-tab.active{background:#10B981;color:#fff;border-color:#10B981;}
        .sl-tab:hover:not(.active){background:rgba(16,185,129,0.04);color:#10B981;border-color:rgba(16,185,129,0.2);}
        .sl-capability-list{display:grid;gap:0.6rem;}
        .sl-capability{display:flex;align-items:flex-start;gap:0.75rem;padding:0.75rem 1rem;border-radius:10px;background:#fff;border:1px solid rgba(0,0,0,0.03);font-size:0.88rem;color:rgba(15,23,42,0.55);line-height:1.6;}
        .sl-check{color:#10B981;font-size:1rem;flex-shrink:0;margin-top:1px;}

        /* CRM FEATURES */
        .sl-crm-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:1.25rem;}
        .sl-crm-card{padding:2rem;border-radius:18px;background:#fff;border:1px solid rgba(0,0,0,0.04);transition:all 0.3s;}
        .sl-crm-card:hover{transform:translateY(-4px);box-shadow:0 15px 40px rgba(0,0,0,0.05);}
        .sl-crm-title{font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:1rem;margin-bottom:0.5rem;}
        .sl-crm-desc{font-size:0.85rem;color:rgba(15,23,42,0.4);line-height:1.7;}

        /* INTEGRATIONS */
        .sl-int-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:1.25rem;}
        .sl-int-group{padding:1.5rem;border-radius:16px;background:#fff;border:1px solid rgba(0,0,0,0.04);}
        .sl-int-group-title{font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:0.82rem;color:#0F172A;margin-bottom:0.75rem;}
        .sl-int-list{list-style:none;}
        .sl-int-list li{padding:0.25rem 0;font-size:0.8rem;color:rgba(15,23,42,0.4);display:flex;align-items:center;gap:0.4rem;}

        /* CASE STUDIES */
        .sl-cases{display:grid;gap:1.25rem;}
        .sl-case{border-radius:20px;background:#fff;border:1px solid rgba(0,0,0,0.04);overflow:hidden;transition:all 0.3s;cursor:pointer;}
        .sl-case:hover{box-shadow:0 15px 40px rgba(0,0,0,0.06);}
        .sl-case-header{display:flex;align-items:center;justify-content:space-between;padding:1.5rem 2rem;gap:1rem;}
        .sl-case-tag{font-size:0.65rem;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;padding:0.3rem 0.75rem;border-radius:50px;color:#fff;flex-shrink:0;}
        .sl-case-title{font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:1rem;flex:1;line-height:1.4;}
        .sl-case-toggle{font-size:1.2rem;color:rgba(15,23,42,0.2);transition:transform 0.3s;}
        .sl-case-body{padding:0 2rem 2rem;border-top:1px solid rgba(0,0,0,0.04);}
        .sl-case-profile{font-size:0.82rem;color:rgba(15,23,42,0.4);margin:1rem 0;line-height:1.7;font-style:italic;}
        .sl-case-results{list-style:none;display:grid;gap:0.5rem;}
        .sl-case-results li{font-size:0.85rem;color:rgba(15,23,42,0.55);display:flex;align-items:flex-start;gap:0.5rem;line-height:1.5;}

        /* AUDIENCES */
        .sl-audiences{display:grid;grid-template-columns:repeat(3,1fr);gap:1.25rem;}
        .sl-audience{padding:2.5rem;border-radius:20px;background:#fff;border:1px solid rgba(0,0,0,0.04);transition:all 0.3s;}
        .sl-audience:hover{transform:translateY(-4px);box-shadow:0 15px 40px rgba(0,0,0,0.05);}
        .sl-audience-icon{font-size:2rem;margin-bottom:1rem;}
        .sl-audience-title{font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:1.1rem;margin-bottom:0.5rem;}
        .sl-audience-desc{font-size:0.85rem;color:rgba(15,23,42,0.4);line-height:1.7;margin-bottom:1.25rem;}
        .sl-audience-list{list-style:none;display:grid;gap:0.4rem;}
        .sl-audience-list li{font-size:0.82rem;color:rgba(15,23,42,0.5);display:flex;align-items:flex-start;gap:0.5rem;line-height:1.5;}

        /* AI STEPS */
        .sl-steps{display:grid;grid-template-columns:repeat(5,1fr);gap:1.5rem;}
        .sl-step{padding:0 0 0 1.5rem;border-left:2px solid rgba(16,185,129,0.15);}
        .sl-step-num{font-family:'Space Grotesk',sans-serif;font-size:2rem;font-weight:700;color:rgba(16,185,129,0.15);margin-bottom:0.4rem;}
        .sl-step-title{font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:0.95rem;margin-bottom:0.4rem;}
        .sl-step-desc{font-size:0.8rem;color:rgba(15,23,42,0.35);line-height:1.6;}

        /* TESTIMONIALS */
        .sl-testimonials{display:grid;grid-template-columns:repeat(2,1fr);gap:1.25rem;}
        .sl-testimonial{padding:2.5rem;border-radius:20px;background:#fff;border:1px solid rgba(0,0,0,0.04);transition:all 0.3s;}
        .sl-testimonial:hover{transform:translateY(-3px);box-shadow:0 12px 35px rgba(0,0,0,0.05);}
        .sl-testimonial-quote{font-size:0.9rem;color:rgba(15,23,42,0.5);line-height:1.8;margin-bottom:1.5rem;font-style:italic;}
        .sl-testimonial-author{font-weight:700;font-size:0.82rem;}
        .sl-testimonial-company{font-size:0.75rem;color:rgba(15,23,42,0.35);}
        .sl-testimonial-type{display:inline-block;margin-top:0.5rem;padding:0.2rem 0.6rem;border-radius:50px;font-size:0.62rem;font-weight:600;background:rgba(16,185,129,0.06);color:#10B981;}

        /* DARK SECTIONS */
        .sl-dark{background:#0F172A;color:#fff;padding:6rem 2rem;}
        .sl-dark .sl-label{color:#10B981;}
        .sl-dark .sl-title{color:#fff;}
        .sl-dark .sl-subtitle{color:rgba(255,255,255,0.4);}

        /* CTA SEC */
        .sl-cta-sec{text-align:center;padding:6rem 2rem;background:linear-gradient(135deg,#10B981,#059669);color:#fff;border-radius:32px;margin:0 3rem 4rem;position:relative;overflow:hidden;}
        .sl-cta-sec h2{font-family:'Space Grotesk',sans-serif;font-size:clamp(2rem,4vw,3rem);font-weight:700;margin-bottom:1rem;position:relative;}
        .sl-cta-sec p{color:rgba(255,255,255,0.7);margin-bottom:2rem;max-width:550px;margin-left:auto;margin-right:auto;position:relative;line-height:1.7;font-size:0.92rem;}
        .sl-cta-white{padding:0.75rem 2rem;border-radius:50px;background:#fff;color:#10B981;font-weight:700;font-size:0.88rem;border:none;cursor:pointer;text-decoration:none;transition:all 0.3s;display:inline-block;}
        .sl-cta-white:hover{transform:translateY(-2px);box-shadow:0 8px 30px rgba(0,0,0,0.2);}
        .sl-trust{display:flex;flex-wrap:wrap;gap:0.75rem;justify-content:center;margin-top:2rem;}
        .sl-trust-item{font-size:0.72rem;color:rgba(255,255,255,0.6);display:flex;align-items:center;gap:0.3rem;}

        /* FOOTER */
        .sl-footer{padding:3rem 2rem;max-width:1100px;margin:0 auto;}
        .sl-footer-grid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:3rem;margin-bottom:2rem;}
        .sl-footer-brand{font-family:'Space Grotesk',sans-serif;font-weight:700;font-size:1rem;margin-bottom:0.5rem;}
        .sl-footer-desc{font-size:0.78rem;color:rgba(15,23,42,0.3);line-height:1.6;}
        .sl-footer-col-title{font-size:0.68rem;font-weight:700;text-transform:uppercase;letter-spacing:0.1em;color:rgba(15,23,42,0.25);margin-bottom:0.75rem;}
        .sl-footer-link{display:block;font-size:0.78rem;color:rgba(15,23,42,0.4);text-decoration:none;padding:0.2rem 0;transition:color 0.2s;}
        .sl-footer-link:hover{color:#10B981;}
        .sl-footer-bottom{text-align:center;font-size:0.68rem;color:rgba(15,23,42,0.2);padding-top:2rem;border-top:1px solid rgba(0,0,0,0.04);}

        @media(max-width:768px){
          .sl-nav{padding:1rem 1.5rem;}.sl-nav-links{display:none;}
          .sl-stats{grid-template-columns:repeat(2,1fr);margin:0 1rem;margin-top:-2rem;}.sl-stats .sl-stat:last-child{display:none;}
          .sl-pillars,.sl-crm-grid,.sl-audiences,.sl-testimonials{grid-template-columns:1fr;}
          .sl-steps{grid-template-columns:1fr;}
          .sl-cta-sec{margin:0 1rem 3rem;border-radius:20px;}
          .sl-footer-grid{grid-template-columns:1fr;}
          .sl-tabs{overflow-x:auto;flex-wrap:nowrap;padding-bottom:0.5rem;}
        }
      `}</style>

      <div className="sl">
        {/* ═══ NAV ═══ */}
        <nav className="sl-nav">
          <a href={`${bp}/`} className="sl-nav-logo"><img src={`${bp}/logos/aqurion-sales-icon.png`} alt="" />Aqurion Sales</a>
          <div className="sl-nav-links">
            <a href="#platform" className="sl-nav-link">Platform</a>
            <a href="#cases" className="sl-nav-link">Case Studies</a>
            <a href="#audiences" className="sl-nav-link">Who We Serve</a>
            <a href="#contact" className="sl-nav-link">Contact</a>
          </div>
          <a href="#contact" className="sl-cta">Request a Demo</a>
        </nav>

        {/* ═══ HERO ═══ */}
        <section className="sl-hero">
          <div className="sl-hero-bg" /><div className="sl-hero-orb1" /><div className="sl-hero-orb2" />
          <div className="sl-hero-content">
            <Rv><div className="sl-eyebrow">AI-Powered Sales Automation • An Aqurion Holdings Company</div></Rv>
            <Rv d={0.1}><h1>Your Sales Team Just Got a <span className="sl-grad">24/7 AI Workforce</span>.</h1></Rv>
            <Rv d={0.2}><p className="sl-hero-sub">Aqurion Sales automates the conversations, follow-ups, and pipeline management that cost your team hours every day — so your people can focus on building relationships and closing deals.</p></Rv>
            <Rv d={0.3}><p className="sl-hero-body">From AI chatbots and email automation to intelligent phone bots and a fully integrated CRM, Aqurion Sales gives businesses of every size the infrastructure to compete, scale, and win.</p></Rv>
            <Rv d={0.35}><p className="sl-hero-proof">Trusted by startups, mid-market companies, and Fortune 500 enterprises — across 12 industries.</p></Rv>
            <Rv d={0.4}><div className="sl-hero-btns"><a href="#contact" className="sl-cta" style={{ padding: "0.75rem 2.5rem" }}>Request a Demo</a><a href="#platform" className="sl-cta-outline">See How It Works →</a></div></Rv>
          </div>
        </section>

        {/* ═══ STATS BAR ═══ */}
        <Rv><div className="sl-stats">{heroStats.map(s => <div key={s.label} className="sl-stat"><div className="sl-stat-val">{s.val}</div><div className="sl-stat-label">{s.label}</div></div>)}</div></Rv>

        {/* ═══ PAIN POINTS ═══ */}
        <section className="sl-section">
          <Rv><div className="sl-label">The Problem</div><h2 className="sl-title">The Old Way of Selling Is Costing You Deals You Don't Even Know You're Losing.</h2></Rv>
          <Rv d={0.1}><p className="sl-subtitle">In today's market, the company that responds first wins. The company that follows up consistently wins. Most businesses are failing at all three — not because of effort, but because of tools.</p></Rv>
          <div className="sl-pain-grid">
            {painPoints.map((p, i) => <Rv key={i} d={i * 0.05}><div className="sl-pain"><div className="sl-pain-icon">✕</div><div className="sl-pain-text">{p}</div></div></Rv>)}
          </div>
          <Rv d={0.4}><p style={{ marginTop: "2rem", fontSize: "0.92rem", color: "rgba(15,23,42,0.5)", lineHeight: 1.8, maxWidth: 700 }}>Aqurion Sales was built specifically to solve these problems — for a Fortune 500 enterprise with thousands of reps, and for a three-person startup that can't afford to miss a single lead.</p></Rv>
        </section>

        {/* ═══ PLATFORM OVERVIEW ═══ */}
        <section id="platform" className="sl-section" style={{ textAlign: "center" }}>
          <Rv><div className="sl-label">Platform</div><h2 className="sl-title">One Platform. Every Conversation. Complete Automation.</h2></Rv>
          <Rv d={0.1}><p className="sl-subtitle" style={{ margin: "0 auto 3rem" }}>Aqurion Sales is a fully integrated AI sales automation platform that unifies every channel your prospects use — and automates the work it takes to convert them. It's not just a CRM. It's your entire sales operation, running intelligently.</p></Rv>
          <div className="sl-pillars">
            {platformPillars.map((p, i) => (
              <Rv key={p.title} d={i * 0.08}><div className="sl-pillar" style={{ "--accent": p.color } as React.CSSProperties}>
                <div className="sl-pillar-icon" style={{ background: `${p.color}10` }}>{p.icon}</div>
                <div className="sl-pillar-title">{p.title}</div>
                <div className="sl-pillar-desc">{p.desc}</div>
              </div></Rv>
            ))}
          </div>
        </section>

        {/* ═══ AI DEEP DIVE ═══ */}
        <div className="sl-dark">
          <div style={{ maxWidth: 1100, margin: "0 auto" }}>
            <Rv><div className="sl-label">AI Automation</div><h2 className="sl-title" style={{ color: "#fff" }}>AI Bots That Work While You Sleep, Scale While You Grow, and Never Miss a Lead.</h2></Rv>
            <Rv d={0.1}><p className="sl-subtitle">Aqurion's AI automation layer is the engine that separates the platform from every traditional CRM and sales tool on the market.</p></Rv>
            <div className="sl-tabs">
              {["🤖 AI Chatbots", "📧 AI Email Bots", "📞 AI Phone Bots"].map((t, i) => (
                <button key={t} className={`sl-tab${activeTab === i ? " active" : ""}`} onClick={() => setActiveTab(i)} style={activeTab === i ? {} : { background: "rgba(255,255,255,0.04)", borderColor: "rgba(255,255,255,0.08)", color: "rgba(255,255,255,0.4)" }}>{t}</button>
              ))}
            </div>
            <AnimatePresence mode="wait">
              <motion.div key={activeTab} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} transition={{ duration: 0.3 }}>
                <div className="sl-capability-list">
                  {(activeTab === 0 ? chatbotCapabilities : activeTab === 1 ? emailCapabilities : phoneCapabilities).map((c, i) => (
                    <div key={i} className="sl-capability" style={{ background: "rgba(255,255,255,0.03)", borderColor: "rgba(255,255,255,0.04)" }}>
                      <span className="sl-check">✓</span><span style={{ color: "rgba(255,255,255,0.6)" }}>{c}</span>
                    </div>
                  ))}
                </div>
              </motion.div>
            </AnimatePresence>
          </div>
        </div>

        {/* ═══ INTELLIGENT CRM ═══ */}
        <section className="sl-section">
          <Rv><div className="sl-label">CRM</div><h2 className="sl-title">A CRM That Knows What to Do Next — Before Your Rep Does.</h2></Rv>
          <Rv d={0.1}><p className="sl-subtitle">Most CRMs are record-keeping systems. Aqurion's CRM is a decision-making engine. It captures data automatically, flags risks in real time, and tells you what to do to close.</p></Rv>
          <div className="sl-crm-grid">
            {crmFeatures.map((f, i) => (
              <Rv key={f.title} d={i * 0.08}><div className="sl-crm-card">
                <div className="sl-crm-title">{f.title}</div>
                <div className="sl-crm-desc">{f.desc}</div>
              </div></Rv>
            ))}
          </div>
        </section>

        {/* ═══ ECOSYSTEM & INTEGRATIONS ═══ */}
        <section className="sl-section" style={{ textAlign: "center" }}>
          <Rv><div className="sl-label">Integrations</div><h2 className="sl-title">Built to Work With Everything. Built to Work Best With Aqurion.</h2></Rv>
          <Rv d={0.1}><p className="sl-subtitle" style={{ margin: "0 auto 3rem" }}>Aqurion Sales connects natively with the Aqurion ecosystem and integrates with 250+ external platforms your team already uses.</p></Rv>
          <div className="sl-int-grid">
            {Object.entries(integrations).map(([group, tools], i) => (
              <Rv key={group} d={i * 0.06}><div className="sl-int-group">
                <div className="sl-int-group-title">{group}</div>
                <ul className="sl-int-list">{tools.map(t => <li key={t}><span style={{ color: "#10B981" }}>•</span> {t}</li>)}</ul>
              </div></Rv>
            ))}
          </div>
        </section>

        {/* ═══ CASE STUDIES ═══ */}
        <section id="cases" className="sl-section">
          <Rv><div className="sl-label">Case Studies</div><h2 className="sl-title">Real Businesses. Real Automation. Real Results.</h2></Rv>
          <Rv d={0.1}><p className="sl-subtitle">Across every industry and every business size, Aqurion Sales is helping organizations automate their sales process and grow faster than their competition.</p></Rv>
          <div className="sl-cases">
            {caseStudies.map((cs, i) => (
              <Rv key={i} d={i * 0.06}>
                <div className="sl-case" onClick={() => setExpandedCase(expandedCase === i ? null : i)}>
                  <div className="sl-case-header">
                    <span className="sl-case-tag" style={{ background: cs.color }}>{cs.tag}</span>
                    <div className="sl-case-title">{cs.title}</div>
                    <span className="sl-case-toggle" style={{ transform: expandedCase === i ? "rotate(180deg)" : "rotate(0)" }}>▾</span>
                  </div>
                  <AnimatePresence>
                    {expandedCase === i && (
                      <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.3 }} style={{ overflow: "hidden" }}>
                        <div className="sl-case-body">
                          <div className="sl-case-profile">{cs.profile}</div>
                          <ul className="sl-case-results">
                            {cs.results.map((r, j) => <li key={j}><span style={{ color: cs.color }}>✓</span> {r}</li>)}
                          </ul>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              </Rv>
            ))}
          </div>
        </section>

        {/* ═══ WHO WE SERVE ═══ */}
        <section id="audiences" className="sl-section" style={{ textAlign: "center" }}>
          <Rv><div className="sl-label">Who We Serve</div><h2 className="sl-title">Built for the Startup That Can't Afford to Miss a Lead.<br />Scaled for the Enterprise That Can't Afford Inefficiency.</h2></Rv>
          <div className="sl-audiences">
            {audiences.map((a, i) => (
              <Rv key={a.title} d={i * 0.1}><div className="sl-audience">
                <div className="sl-audience-icon">{a.icon}</div>
                <div className="sl-audience-title">{a.title}</div>
                <div className="sl-audience-desc">{a.desc}</div>
                <ul className="sl-audience-list">{a.bullets.map(b => <li key={b}><span style={{ color: "#10B981" }}>✓</span> {b}</li>)}</ul>
              </div></Rv>
            ))}
          </div>
        </section>

        {/* ═══ AI STRATEGY ═══ */}
        <div className="sl-dark">
          <div style={{ maxWidth: 1100, margin: "0 auto" }}>
            <Rv><div className="sl-label">AI Strategy</div><h2 className="sl-title" style={{ color: "#fff" }}>AI Isn't Coming for Sales. It's Already Here.</h2></Rv>
            <Rv d={0.1}><p className="sl-subtitle">Companies that integrate AI into their sales process now will be nearly impossible to catch in three years. We don't just sell software — we partner with businesses to build AI sales strategies that actually work.</p></Rv>
            <div className="sl-steps">
              {aiSteps.map((s, i) => (
                <Rv key={s.num} d={i * 0.1}><div className="sl-step" style={{ borderColor: "rgba(16,185,129,0.2)" }}>
                  <div className="sl-step-num" style={{ color: "rgba(16,185,129,0.2)" }}>{s.num}</div>
                  <div className="sl-step-title" style={{ color: "#fff" }}>{s.title}</div>
                  <div className="sl-step-desc" style={{ color: "rgba(255,255,255,0.35)" }}>{s.desc}</div>
                </div></Rv>
              ))}
            </div>
          </div>
        </div>

        {/* ═══ TESTIMONIALS ═══ */}
        <section className="sl-section" style={{ textAlign: "center" }}>
          <Rv><div className="sl-label">Testimonials</div><h2 className="sl-title">What Our Clients Say</h2></Rv>
          <div className="sl-testimonials">
            {testimonials.map((t, i) => (
              <Rv key={i} d={i * 0.08}><div className="sl-testimonial">
                <div className="sl-testimonial-quote">"{t.quote}"</div>
                <div className="sl-testimonial-author">— {t.author}</div>
                <div className="sl-testimonial-company">{t.company}</div>
                <div className="sl-testimonial-type">{t.type}</div>
              </div></Rv>
            ))}
          </div>
        </section>

        {/* ═══ FINAL CTA ═══ */}
        <Rv><section id="contact" className="sl-cta-sec">
          <h2>Your Competition Is Already Automating.<br />Let's Make Sure You're Ahead.</h2>
          <p>Book a strategy session. We'll walk through your current sales process, identify your highest-impact automation opportunities, and show you exactly what Aqurion Sales would look like for your business.</p>
          <a href="mailto:Chat@AquironSales.com" className="sl-cta-white">Request a Demo — No Commitment Required</a>
          <div className="sl-trust">
            {trustSignals.map(t => <span key={t} className="sl-trust-item"><span style={{ color: "#A7F3D0" }}>✓</span> {t}</span>)}
          </div>
        </section></Rv>

        {/* ═══ FOOTER ═══ */}
        <footer className="sl-footer">
          <div className="sl-footer-grid">
            <div><div className="sl-footer-brand">Aqurion Sales</div><div className="sl-footer-desc">An Aqurion Holdings Company. AI-powered sales automation for businesses of every size.</div></div>
            <div><div className="sl-footer-col-title">Ecosystem</div><a href="https://Aqurion.net" className="sl-footer-link">Aqurion Holdings</a><a href="https://Aqurion.AI" className="sl-footer-link">Aqurion AI</a><a href="https://AqurionMarketing.com" className="sl-footer-link">Marketing</a><a href="https://AqurionDev.com" className="sl-footer-link">Development</a></div>
            <div><div className="sl-footer-col-title">Contact</div><a href="mailto:Chat@AquironSales.com" className="sl-footer-link">Chat@AquironSales.com</a><a href="tel:+18882787106" className="sl-footer-link">1-888-AQUR-10-N (Press 5)</a></div>
          </div>
          <div className="sl-footer-bottom">© {new Date().getFullYear()} Aqurion Sales — An Aqurion Holdings Company</div>
        </footer>
      </div>
    </>
  );
}
